#!/usr/bin/env bash
# =============================================================================
# run-playbook.sh
# Wrapper script used by cron to execute Ansible playbooks with logging.
#
# Usage (called by cron):
#   run-playbook.sh <playbook_path> <vars_file> <inventory> <log_dir> [extra_vars] [limit]
#
# Generated by the ansible-controller playbook. Do not edit manually.
# =============================================================================

set -euo pipefail

PLAYBOOK="$1"
VARS_FILE="$2"
INVENTORY="$3"
LOG_DIR="$4"
EXTRA_VARS="${5:-}"
LIMIT="${6:-}"

# Derive a log filename from the playbook path and current timestamp
PLAYBOOK_NAME=$(basename "$(dirname "$PLAYBOOK")")
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")
LOG_FILE="${LOG_DIR}/${PLAYBOOK_NAME}_${TIMESTAMP}.log"

# Ensure log directory exists
mkdir -p "$LOG_DIR"

echo "=======================================================" | tee "$LOG_FILE"
echo " Ansible Playbook Run" | tee -a "$LOG_FILE"
echo " Playbook:   $PLAYBOOK" | tee -a "$LOG_FILE"
echo " Vars file:  $VARS_FILE" | tee -a "$LOG_FILE"
echo " Inventory:  $INVENTORY" | tee -a "$LOG_FILE"
echo " Start time: $(date)" | tee -a "$LOG_FILE"
echo "=======================================================" | tee -a "$LOG_FILE"

# Build the ansible-playbook command
CMD=(ansible-playbook "$PLAYBOOK" -i "$INVENTORY" -e "@${VARS_FILE}")

if [[ -n "$EXTRA_VARS" ]]; then
    CMD+=(-e "$EXTRA_VARS")
fi

if [[ -n "$LIMIT" ]]; then
    CMD+=(-l "$LIMIT")
fi

# Run the playbook, capturing output and exit code
EXIT_CODE=0
"${CMD[@]}" 2>&1 | tee -a "$LOG_FILE" || EXIT_CODE=$?

echo "=======================================================" | tee -a "$LOG_FILE"
echo " End time:   $(date)" | tee -a "$LOG_FILE"
echo " Exit code:  $EXIT_CODE" | tee -a "$LOG_FILE"
echo "=======================================================" | tee -a "$LOG_FILE"

if [[ $EXIT_CODE -ne 0 ]]; then
    logger -t ansible-cron "FAILED: $PLAYBOOK_NAME (exit $EXIT_CODE) — see $LOG_FILE"
    exit "$EXIT_CODE"
else
    logger -t ansible-cron "SUCCESS: $PLAYBOOK_NAME — see $LOG_FILE"
fi
